=== dzmitry-liashenka/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element type="groupType" name="group" minOccurs="0" maxOccurs="100"/>
            </xs:sequence>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="emailType" name="email" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gmail@gmail.com"/>
            <xs:enumeration value="admin@javaops.ru"/>
            <xs:enumeration value="mail@yandex.ru"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="groupStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="groupType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="groupNameType" name="grp" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="groupNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="basejava01"/>
            <xs:enumeration value="basejava02"/>
            <xs:enumeration value="basejava03"/>
            <xs:enumeration value="topjava01"/>
            <xs:enumeration value="topjava02"/>
            <xs:enumeration value="topjava03"/>
            <xs:enumeration value="masterjava01"/>
            <xs:enumeration value="masterjava02"/>
            <xs:enumeration value="masterjava03"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:element name="Project" >
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element type="xs:string" name="description"/>
            </xs:sequence>
            <xs:attribute type="groupStatusType" name="status" use="required"/>
            <xs:attribute type="groupNameType" name="group" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dzmitry-liashenka/masterjava/src/main/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">

    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Ralf Hirsch</fullName>
            <group grp="basejava01"/>
            <group grp="topjava02" />
            <group grp="masterjava03" />
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru">
            <fullName>Admin</fullName>
            <group grp="masterjava03" />
            <group grp="topjava03" />
            <group grp="topjava02" />
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
            <fullName>Sebastian Storch</fullName>
            <group grp="basejava01"/>
            <group grp="topjava02" />
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project status="FINISHED" group="basejava01">
            <name>BaseJava</name>
            <description>Java-разработчик веб-приложений</description>
        </Project>
        <Project status="FINISHED" group="topjava01">
            <name>TopJava</name>
            <description>Enterprise Java-разработчик</description>
        </Project>
        <Project status="CURRENT" group="topjava02">
            <name>TopJava</name>
            <description>Enterprise Java-разработчик</description>
        </Project>
        <Project status="REGISTERING" group="topjava03">
            <name>TopJava</name>
            <description>Enterprise Java-разработчик</description>
        </Project>
        <Project status="FINISHED" group="masterjava01">
            <name>MasterJava</name>
            <description>Многомодульный Maven, многопоточность, JavaEE</description>
        </Project>
        <Project status="CURRENT" group="masterjava02">
            <name>MasterJava</name>
            <description>Многомодульный Maven, многопоточность, JavaEE</description>
        </Project>
        <Project status="REGISTERING" group="masterjava03">
            <name>MasterJava</name>
            <description>Многомодульный Maven, многопоточность, JavaEE</description>
        </Project>
    </Projects>
</Payload>

<!--
1: Изменить XML схему:
1.1 добавить проекты. Имеют название (например topjava, masterjava) и описание
1.2 добавить группы. Они имеют название и тип (REGISTERING/CURRENT/FINISHED) и принадлежат проекту.
 Например проект topjava, группы topjava01,topjava02, ..
1.3 сделать User.email аттрибутом.
1.4 реализовать принадлежность участников разным группам (Admin состоит в группах topjava07, topjava08, masterjava01)
2: Дополнить xml тестовыми данными.
3: Реализовать класс MainXml, которые принимает параметром имя проекта в тестовом xml
и выводит отсортированный список его участников (использовать JAXB).
-->
